### ISSUE TITLE
Relógio mudando de posição na transição do 59 -> 0 e 9 -> 10

### ISSUE THREAD

**Issue by Artfloriani** [ubirataantunes/relogio-em-js#1]
Olá @ubirataantunes, 

Bem legal a iniciativa de fazer esse projeto 🎉 

Enquanto estava olhando o código, percebi que você optou por utilizar o DOM (`divs`) pra corrigir o problema de colocar o zero a esquerda nos dígitos de 0 a 9. O problema é que essa manipulação do DOM ta gerando um problema de layout:

![Screen Recording 2022-06-24 at 10 09 58](https://user-images.githubusercontent.com/6491691/175543136-4f1359c9-64e4-4329-aa25-6b558aca5da3.gif)

Uma possível solução é resolver o problema do zero a esquerda só pelo Javascript:

```
        let sec = date.getSeconds();
        if (sec < 10) {
            sec = `0${sec}`;
        }   
        unitySeconds.innerHTML = sec;
```

**Comment by ubirataantunes** [comment]
Olá, Arthur! 

Primeiramente muito obrigado pela atenção dada ao meu projeto, realmente esse é um problema que eu estou estudando corrigir pois eu planejo utilizá-lo num possível app de agenda ou algo do tipo, embora eu não tivesse pego o código para analisar novamente. 

Irei experimentar sua ideia assim que possível para tentar corrigir esse probleminha. 

Muito obrigado 🙏🏽

**Comment by ubirataantunes** [comment]
> Olá @ubirataantunes, 
> 
> 
> 
> Bem legal a iniciativa de fazer esse projeto 🎉 
> 
> 
> 
> Enquanto estava olhando o código, percebi que você optou por utilizar o DOM (`divs`) pra corrigir o problema de colocar o zero a esquerda nos dígitos de 0 a 9. O problema é que essa manipulação do DOM ta gerando um problema de layout:
> 
> 
> 
> ![Screen Recording 2022-06-24 at 10 09 58](https://user-images.githubusercontent.com/6491691/175543136-4f1359c9-64e4-4329-aa25-6b558aca5da3.gif)
> 
> 
> 
> Uma possível solução é resolver o problema do zero a esquerda só pelo Javascript:
> 
> 
> 
> ```
> 
>         let sec = date.getSeconds();
> 
>         if (sec < 10) {
> 
>             sec = `0${sec}`;
> 
>         }   
> 
>         unitySeconds.innerHTML = sec;
> 
> ```
> 
> 

Olá, @Artfloriani  

Primeiramente muito obrigado pela atenção dada ao meu projeto, realmente esse é um problema que eu estou estudando corrigir pois eu planejo utilizar esse relógio num possível app de agenda ou algo do tipo, embora eu não tivesse pego o código para analisar novamente. 

Irei experimentar sua ideia assim que possível para tentar corrigir esse probleminha. 

Muito obrigado 🙏🏽

**Comment by ubirataantunes** [comment]
@Artfloriani testei aqui e deu certo, com base no que você me passou eu também fiz algumas mudanças que diminuíram consideravelmente as linhas do meu código e aumentaram a sua eficácia, agora é só felicidade!!!

Muito obrigado!

**Comment by Artfloriani** [comment]
De nada! Agora só felicidade mesmo, boa 👏 

🚀
